# Generated by Django 3.2 on 2021-05-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_articles_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='file',
        ),
    ]
