# Generated by Django 3.2 on 2021-05-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ras_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField(verbose_name='Дата проведения занятия')),
                ('presence', models.BooleanField(verbose_name='Присутсвие на занятии')),
                ('fk_discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.discipline', verbose_name='Дисциплина')),
                ('fk_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
    ]
