# Generated by Django 3.2 on 2021-05-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='fk_student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='fk_student',
            field=models.ManyToManyField(to='main.Student', verbose_name='Студент'),
        ),
    ]
