# Generated by Django 3.2 on 2021-05-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210514_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='presence',
            field=models.CharField(choices=[('Да', 'Присутствует'), ('Нет', 'Отсутствует')], max_length=3, verbose_name='Присутсвие на занятии'),
        ),
    ]
