# Generated by Django 3.2 on 2021-06-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210531_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
