# Generated by Django 3.2 on 2021-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='presence',
            field=models.CharField(choices=[('Контрольная', 'Контрольная'), ('Лабораторная', 'Лабораторная'), ('Практическая', 'Практическая'), ('Итоговая', 'Итоговая')], default=1, max_length=20, verbose_name='Приоритет важности работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='presence',
            field=models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], max_length=20, verbose_name='Присутсвие на занятии'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение'),
        ),
    ]
