# Generated by Django 3.2 on 2021-06-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210601_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='group_name',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='group_name',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='group_name',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='group_name',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='position',
            name='salary_en',
        ),
        migrations.RemoveField(
            model_name='position',
            name='salary_ru',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name_en',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name_ru',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname_en',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname_ru',
        ),
    ]
